### ISSUE TITLE
callee/caller map

### ISSUE THREAD

**Issue by feeshstick** [ProjectIgnis/scrapiyard#25]
What about adding callee and caller entries to functions?

use-case:
1. user wants to see usage of a function; lists card-scripts or library functions using that function.
2. analysing dependencies and data visualization

**Comment by feeshstick** [comment]
can be automatically generated

```json

"AddProcMixN": {
  "source": {
    "path": "assets/repositories/CardScripts/proc_fusion.lua",
    "range": [
      36966,
      37430
    ],
    "callee": {
      "fromNamespace": [
        {
          "name": "AddProcMix",
          "namespace": "Fusion"
        }
      ]
    }
  },
  "documentation": {
    "namespace": "api/namespaces/Fusion.AddProcMixN.yml",
    "function": "api/functions/Fusion/Fusion.AddProcMixN.yml"
  }
},
```

**Comment by that-hatter** [comment]
I'm not sure these should be stored here.

If they are added in the yaml entries, they would considerably bloat the yaml files. If not, then there'll need to be separate files for them, fracturing where information about an entry is stored.

Having scripts to auto-generate them in the repo also makes separating `scrapi-factory` pointless (i.e., why not store the validation script here as well if the repo's going to have scripts anyway?)

Instead, these information could be appended by the loader (e.g. `scrapi-factory`) after parsing the entries. In fact, `factory` already does add the source code info to the entries. That's how `book` is able to link to them.

Some notes about the use cases:
> user wants to see usage of a function; lists card-scripts or library functions using that function.

This is sort of already achievable even without static analysis. Instead of going through the script files, just generate the corresponding github search query for that function. For example, for `Card.IsLevel`, the link "https://github.com/search?q=repo%3AProjectIgnis%2FCardScripts+%3AIsLevel&type=code" could be generated. The search results won't be perfect, but it's good enough for that use.

> analysing dependencies and data visualization

This could be fun but I'm not seeing immediate need for it atm. Would be cool to have some sort of function dependency graph in the future though.

**Comment by feeshstick** [comment]
alrighty. thanks for the reply.
